# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-09 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0002_auto_20191009_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scan',
            name='time_scanned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
