# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0004_remove_scan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsor',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
