# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-28 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0005_event_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sponsor',
        ),
    ]
