# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0007_event_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(default=0),
        ),
    ]
