# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0009_auto_20191104_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
