# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0013_auto_20191104_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
