# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HU_Event_Scanner_App', '0014_auto_20200212_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('add_date', models.DateField()),
                ('chapel_envt_no', models.IntegerField()),
            ],
        ),
    ]
