# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-02 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0015_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='chapel_envt_no',
        ),
    ]
