# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-03 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0016_auto_20200402_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='chapel_envt_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
