# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HU_Event_Scanner_App', '0017_auto_20200403_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='new_scan',
            field=models.BooleanField(default=True),
        ),
    ]
